### ISSUE TITLE
`javancss-maven-plugin` fails on java 8+ codebase

### ISSUE THREAD

**Issue by fbiville** [assertj/assertj-parent-pom#38]
`maven-project-info-reports-plugin` `3.0` is not on Central, `3.0.0` is.
It's blocking `mvn site` from completing.

**Comment by fbiville** [comment]
Here is what I had to change in Assertj-Neo4j to get the site to generate:

1. remove all Java 8 (luckily, was just 3 lines of code to change)
2. override the following plugins:

```
+    <pluginManagement>
+      <plugins>
+        <plugin>
+          <artifactId>maven-site-plugin</artifactId>
+          <version>3.7.1</version>
+        </plugin>
+      </plugins>
+    </pluginManagement>
   </build>

+  <reporting>
+    <plugins>
+      <plugin>
+        <groupId>org.apache.maven.plugins</groupId>
+        <artifactId>maven-project-info-reports-plugin</artifactId>
+        <version>3.0.0</version>
+      </plugin>
+    </plugins>
+  </reporting>
```

**Comment by joel-costigliola** [comment]
So all we need to do is to bump the version of these plugins ?

**Comment by fbiville** [comment]
It seems that works well for code pre-Java 8.
If you got lambdas, method references etc... there will still be parsing errors.

**Comment by joel-costigliola** [comment]
@fbiville we have just released `assertj-parent-pom` 2.2.4, can you give it a try to see if it solved your issue ?

**Comment by fbiville** [comment]
@scordio fixed it https://github.com/joel-costigliola/assertj-neo4j/commit/2667c3ff47a0049f3a9cf780b295e2e10233a04c :)

**Comment by fbiville** [comment]
Oopsie, talked too fast:
```
 $ cd $(mktemp -d) && git clone https://github.com/joel-costigliola/assertj-neo4j.git && mvn site -f assertj-neo4j
```

**Comment by fbiville** [comment]
Now that Assertj Neo4j contains [Java 8+ code](https://github.com/joel-costigliola/assertj-neo4j/blob/45a2223af4e73fb8e87b548d044ec4c81c745935/src/main/java/org/assertj/neo4j/api/InstanceOfAssertFactories.java) again, the site cannot be generated.

**Comment by joel-costigliola** [comment]
living on the edge @fbiville ? 😆

**Comment by scordio** [comment]
The missing support for Java 8 seems to be a JavaNCSS 33.54 issue used by `javancss-maven-plugin`. There is a pull request for it but no feedback for more than a year: codehaus/javancss#3

[The fork from Nokia](https://github.com/nokia/javancss) should have already the fix but I didn't find the updated artifact deployed anywhere.

As the only plugin I see for reporting is `maven-project-info-reports-plugin`, I guess it's the one responsible invoking the `javancss-maven-plugin`. Would it be an option to exclude the JavaNCSS report from its execution? (Not sure yet how to do it, I'll investigate a bit more later on)

**Comment by scordio** [comment]
`javancss-maven-plugin` is currently triggered by the parent POM, therefore the issue should happen in any child project. @joel-costigliola and @fbiville, how are `assertj-core` and `assertj-neo4j` different from `mvn site` point of view? I don't understand why this is not an issue for `assertj-core`.

**Comment by fbiville** [comment]
I assume there is no Java 8+ syntax in `assertj-core` code yet?

**Comment by scordio** [comment]
There is [a bunch of it](https://github.com/joel-costigliola/assertj-core/blob/master/src/main/java/org/assertj/core/api/InstanceOfAssertFactories.java) :-) And the same issue is happening if I execute `mvn site` on `assertj-core`.

@joel-costigliola is `javancss-maven-plugin` really needed or can we get rid of it from the parent pom?

**Comment by fbiville** [comment]
I'm currently in touch with Hervé Boutémy, Apache Maven committer. There may be a way to get Java 8 support into the Java NCSS. We'll have to wait for a few days when Hervé is back from vacation.

**Comment by fbiville** [comment]
See https://github.com/codehaus/javancss/pull/3#issuecomment-519262325

**Comment by scordio** [comment]
Created JavaNCSS/javancss#3

**Comment by scordio** [comment]
I tried to create a PR on top of the existing code but there is at least one issue I am not able to solve, therefore I closed my PR (see https://github.com/codehaus/javancss/pull/3#issuecomment-520074886)

**Comment by scordio** [comment]
Related: JavaNCSS/javancss#4

**Comment by scordio** [comment]
`javancss-maven-plugin` has been removed in #156.
