### ISSUE TITLE
Release 2.2.8 version - remove references to assertj.org

### ISSUE THREAD

**Issue by agabrys** [assertj/assertj-parent-pom#74]
#### Summary
The `assertj.org` domain points to dangerous pages (contain malware). Some of them are even blocked by network providers and browsers. The latest release ([2.2.7](https://github.com/assertj/assertj-parent-pom/releases/tag/assertj-parent-pom-2.2.7)) still points to it. The URL has been fixed 3 months ago #45, but it has not been released yet.

It would be great it the parent 2.2.8 could be released ASAP.

I would also consider redeploy older parents with an updated URL. At this moment a lot of Maven project pages points to the dangerous page:

![maven-documentation](https://user-images.githubusercontent.com/10604335/93524477-d5466f00-f934-11ea-9a82-2ea78ceca281.png)

**Comment by KroArtem** [comment]
@joel-costigliola , I believe this one can be closed?

**Comment by scordio** [comment]
Reference fixed in 5274a20f670072750f43c3f27d798a5f9edca259.
